# Generated by Django 6.0.6 on 2026-06-20 01:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Isncricao',
            new_name='Inscricao',
        ),
    ]
