# Generated by Django 6.0.6 on 2026-06-20 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_rename_isncricao_inscricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscricao',
            old_name='prsenca_confirmada',
            new_name='presenca_confirmada',
        ),
    ]
