# Generated by Django 6.0.6 on 2026-06-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_rename_prsenca_confirmada_inscricao_presenca_confirmada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='template_certificados',
            new_name='template_certificado',
        ),
        migrations.AlterField(
            model_name='evento',
            name='carga_horaria',
            field=models.IntegerField(help_text='Carga horária em horas'),
        ),
    ]
