# Generated by Django 6.0.6 on 2026-06-21 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alunoperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_fim_inscricoes',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 21, 4, 57, 20, 69413, tzinfo=datetime.timezone.utc), verbose_name='Fim das Inscrições'),
            preserve_default=False,
        ),
    ]
