# Generated by Django 6.0.6 on 2026-06-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_evento_data_fim_inscricoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
